version: '3'
services:

  dsw_server:
    image: {SERVER_IMAGE}
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./server/application.yml:/application/engine-wizard/config/application.yml
      - ./server/integration.yml:/application/engine-wizard/config/integration.yml
    links:
      - mongo

  dsw_client:
    image: {CLIENT_IMAGE}
    restart: always
    ports:
      - 8080:80
    environment:
      - API_URL=http://localhost:3000

  mongo:
    image: mongo:3.0.15
    restart: always
    ports:
      - 27017:27017
    command: mongod
