name: DSW E2E Tests

on: [push]

jobs:
  dsw-e2e:
    name: Run DSW E2E Tests
    runs-on: ubuntu-16.04

    env:
      SERVER_IMAGE: datastewardshipwizard/wizard-server:latest
      CLIENT_IMAGE: datastewardshipwizard/wizard-client:latest
      DOCWORKER_IMAGE: datastewardshipwizard/document-worker:latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: |
        docker login -u "$PRIVATE_REGISTRY_USERNAME" -p "$PRIVATE_REGISTRY_PASSWORD" "$PRIVATE_REGISTRY_URL"
        make clean
        make init
      env:
        PRIVATE_REGISTRY_URL: ${{ secrets.PRIVATE_REGISTRY_URL }}
        PRIVATE_REGISTRY_USERNAME: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
        PRIVATE_REGISTRY_PASSWORD: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

    - name: Start DS Wizard
      run: |
        make start
        make wait

    - name: Run Cypress
      uses: cypress-io/github-action@v1
      with:
        browser: chrome
        headless: true
        record: true
        parallel: true
        group: 'DSW E2E Test @ GitHub Actions'
      env:
        CYPRESS_RETRIES: 3
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
